version: "3.8"

services:
  # Compute
  redis-queue:
    image: kubasz51/faasm-redis:${REDIS_VERSION}
    ports:
      - "6379:6379"

  # Compute
  worker:
    image: kubasz51/faasm-worker:${FAASM_VERSION}
    init: true
    security_opt:
      - seccomp:unconfined
    # Allows for tracy thread&ctx switch tracking to work better
    pid: "host"
    ulimits:
      nofile:
        soft: 1073741824
        hard: 1073741824
    ports:
      - "8080:8080"
      #      - "5000:5000"
      - "8003-8010:8003-8010"
      - "8086:8086"
    privileged: true
    volumes:
      - ./:/usr/local/code/faasm/
      - /tmp/faasm-monitor:/var/faasm-monitor
      - ./dev/faasm/build/:${FAASM_BUILD_MOUNT}
      - ./dev/faasm-local/:${FAASM_LOCAL_MOUNT}
      - ./dev/container/shared_store/:/usr/local/faasm/debug_shared_store/
      - ./bin/entrypoint_worker.sh:/entrypoint.sh
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/kernel/debug/tracing:/sys/kernel/debug/tracing
    environment:
      - TINI_SUBREAPER=1
      - CODEGEN_TARGETS=x86_64:skylake;aarch64:thunderx2t99
      - CAPTURE_STDOUT=off
      - CGROUP_MODE=off
      - DELTA_SNAPSHOT_ENCODING=pages=64
      - GLOBAL_MESSAGE_TIMEOUT=600000
      - LOG_LEVEL=debug
      - NETNS_MODE=off
      - REDIS_QUEUE_HOST=${COMPUTE_NODE}
      - REDIS_STATE_HOST=${STORAGE_NODE}
      - SCHEDULER_MONITOR_FILE=/var/faasm-monitor
      - STATE_MODE=redis
      - S3_HOST=${STORAGE_NODE}
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
      - ENDPOINT_HOST=${COMPUTE_NODE}
      - ENDPOINT_NUM_THREADS=4
      - OVERRIDE_CPU_COUNT=${OVERRIDE_CPU_COUNT:-26}
      - VM_ARENA_MODE=${VM_ARENA_MODE:-}
    extra_hosts:
      - "luna-fast:192.168.3.10"
      - "saturno-fast:192.168.3.20"
      - "kone-fast:192.168.3.30"

  # Compute
  nginx:
    image: nginx:latest
    volumes:
      - ./deploy/conf/nginx-local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - worker
    ports:
      - "8081:8080"

  # Both
  cpp:
    image: ${CPP_CLI_IMAGE}
    init: true
    working_dir: /code/cpp
    stdin_open: true
    tty: true
    depends_on:
      - worker
    environment:
      - UPLOAD_HOST=${STORAGE_NODE}
      - INVOKE_HOST=${COMPUTE_NODE}
      - S3_HOST=${STORAGE_NODE}
    extra_hosts:
      - "luna-fast:192.168.3.10"
      - "saturno-fast:192.168.3.20"
      - "kone-fast:192.168.3.30"
    volumes:
      - ./clients/cpp:/code/cpp

  # Both
  python:
    image: ${PYTHON_CLI_IMAGE}
    init: true
    working_dir: /code/python
    stdin_open: true
    tty: true
    depends_on:
      - worker
    environment:
      - UPLOAD_HOST=${STORAGE_NODE}
      - INVOKE_HOST=${COMPUTE_NODE}
      - S3_HOST=${STORAGE_NODE}
    extra_hosts:
      - "luna-fast:192.168.3.10"
      - "saturno-fast:192.168.3.20"
      - "kone-fast:192.168.3.30"
    volumes:
      - ./clients/python:/code/python

  # --- Local cluster dev ---
  # The following containers are only needed for local cluster dev
  # Both
  faasm-cli:
    image: ${FAASM_CLI_IMAGE}
    init: true
    working_dir: /usr/local/code/faasm
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      - worker
      - nginx
    environment:
      - UPLOAD_HOST=${STORAGE_NODE}
      - INVOKE_HOST=${COMPUTE_NODE}
      - LOG_LEVEL=debug
      - REDIS_QUEUE_HOST=${COMPUTE_NODE}
      - REDIS_STATE_HOST=${STORAGE_NODE}
      - S3_HOST=${STORAGE_NODE}
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
    extra_hosts:
      - "luna-fast:192.168.3.10"
      - "saturno-fast:192.168.3.20"
      - "kone-fast:192.168.3.30"
    volumes:
      - ./:/usr/local/code/faasm/
      - ./dev/faasm/build/:/build/faasm/
      - ./dev/faasm-local:/usr/local/faasm
