version: "3"

services:
  # Compute
  redis-queue:
    image: kubasz51/faasm-redis:${REDIS_VERSION}
    ports:
      - "6379:6379"

  # Compute
  worker:
    image: kubasz51/faasm-worker:${FAASM_VERSION}
    security_opt:
      - seccomp:unconfined
    ports:
      - "8080:8080"
#      - "5000:5000"
      - "8003-8010:8003-8010"
      - "8086:8086"
    privileged: true
    volumes:
      - ./:/usr/local/code/faasm/
      - ./dev/faasm/build/:${FAASM_BUILD_MOUNT}
      - ./dev/container/shared_store/:/usr/local/faasm/debug_shared_store/
      - ./bin/entrypoint_worker.sh:/entrypoint.sh
    environment:
      - CAPTURE_STDOUT=off
      - CGROUP_MODE=off
      - DELTA_SNAPSHOT_ENCODING=pages=64
      - GLOBAL_MESSAGE_TIMEOUT=600000
      - LOG_LEVEL=debug
      - NETNS_MODE=off
      - REDIS_QUEUE_HOST=${COMPUTE_NODE}
      - REDIS_STATE_HOST=${STORAGE_NODE}
      - STATE_MODE=redis
      - S3_HOST=${STORAGE_NODE}
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
      - ENDPOINT_HOST=${COMPUTE_NODE}
      - OVERRIDE_CPU_COUNT=15
    extra_hosts:
      - "luna-fast:192.168.3.10"
      - "saturno-fast:192.168.3.20"

  # Compute
  nginx:
    image: nginx:latest
    volumes:
      - ./deploy/conf/nginx-local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - worker
    ports:
      - "8081:8080"

  # Both
  cpp:
    image: ${CPP_CLI_IMAGE}
    working_dir: /code/cpp
    stdin_open: true
    tty: true
    depends_on:
      - worker
    environment:
      - UPLOAD_HOST=${STORAGE_NODE}
      - INVOKE_HOST=${COMPUTE_NODE}
      - S3_HOST=${STORAGE_NODE}
    extra_hosts:
      - "luna-fast:192.168.3.10"
      - "saturno-fast:192.168.3.20"
    volumes:
      - ./clients/cpp:/code/cpp

  # Both
  python:
    image: ${PYTHON_CLI_IMAGE}
    working_dir: /code/python
    stdin_open: true
    tty: true
    depends_on:
      - worker
    environment:
      - UPLOAD_HOST=${STORAGE_NODE}
      - INVOKE_HOST=${COMPUTE_NODE}
      - S3_HOST=${STORAGE_NODE}
    extra_hosts:
      - "luna-fast:192.168.3.10"
      - "saturno-fast:192.168.3.20"
    volumes:
      - ./clients/python:/code/python

  # --- Local cluster dev ---
  # The following containers are only needed for local cluster dev
  # Both
  faasm-cli:
    image: ${FAASM_CLI_IMAGE}
    working_dir: /usr/local/code/faasm
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      - worker
      - nginx
    environment:
      - UPLOAD_HOST=${STORAGE_NODE}
      - INVOKE_HOST=${COMPUTE_NODE}
      - LOG_LEVEL=debug
      - REDIS_QUEUE_HOST=${COMPUTE_NODE}
      - REDIS_STATE_HOST=${STORAGE_NODE}
      - S3_HOST=${STORAGE_NODE}
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
    extra_hosts:
      - "luna-fast:192.168.3.10"
      - "saturno-fast:192.168.3.20"
    volumes:
      - ./:/usr/local/code/faasm/
      - ./dev/faasm/build/:/build/faasm/
      - ./dev/faasm-local:/usr/local/faasm
