version: "3"

services:
  redis-state:
    image: kubasz51/faasm-redis:${FAASM_VERSION}

  redis-queue:
    image: kubasz51/faasm-redis:${FAASM_VERSION}

  upload:
    image: kubasz51/faasm-upload:${FAASM_VERSION}
    ports:
      - "8002:8002"
    depends_on:
      - redis-queue
      - redis-state
    volumes:
      - ./dev/faasm/build/:${FAASM_BUILD_MOUNT}
      - ./dev/wasm/:/usr/local/code/faasm/wasm/
      - ./dev/container/machine-code/:/usr/local/faasm/object/
      - ./dev/container/shared_store/:/usr/local/faasm/shared_store/
    environment:
      - DELTA_SNAPSHOT_ENCODING=pages=64
      - FUNCTION_STORAGE=local
      - LOG_LEVEL=debug
      - PYTHON_CODEGEN=off
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_STATE_HOST=redis-state
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib

  worker:
    image: kubasz51/faasm-worker:${FAASM_VERSION}
    depends_on:
      - upload
    expose:
      - "8080"
    privileged: yes
    volumes:
      - ./:/usr/local/code/faasm/
      - ./dev/faasm/build/:${FAASM_BUILD_MOUNT}
      - ./dev/container/shared_store/:/usr/local/faasm/debug_shared_store/
      - ./bin/entrypoint_worker.sh:/entrypoint.sh
    environment:
      - CAPTURE_STDOUT=off
      - CGROUP_MODE=off
      - DELTA_SNAPSHOT_ENCODING=pages=64
      - FILESERVER_URL=http://${UPLOAD_HOST:-upload}:8002
      - FUNCTION_STORAGE=fileserver
      - GLOBAL_MESSAGE_TIMEOUT=600000
      - LOG_LEVEL=debug
      - NETNS_MODE=off
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_STATE_HOST=redis-state
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
      - ENDPOINT_HOST=worker
      - OVERRIDE_CPU_COUNT=1

  worker-storage:
    image: kubasz51/faasm-worker-storage:${FAASM_VERSION}
    depends_on:
      - upload
    expose:
      - "8080"
    privileged: yes
    volumes:
      - ./:/usr/local/code/faasm/
      - ./dev/faasm/build/:${FAASM_BUILD_MOUNT}
      - ./dev/container/shared_store/:/usr/local/faasm/shared_store/
      - ./bin/entrypoint_worker.sh:/entrypoint.sh
    environment:
      - CAPTURE_STDOUT=off
      - CGROUP_MODE=off
      - DELTA_SNAPSHOT_ENCODING=pages=64
      - FILESERVER_URL=http://${UPLOAD_HOST:-upload}:8002
      - FUNCTION_STORAGE=fileserver
      - IS_STORAGE_NODE=1
      - GLOBAL_MESSAGE_TIMEOUT=600000
      - LOG_LEVEL=debug
      - NETNS_MODE=off
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_STATE_HOST=redis-state
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
      - ENDPOINT_HOST=worker-storage
      - OVERRIDE_CPU_COUNT=1

  nginx:
    image: nginx:latest
    volumes:
      - ./deploy/conf/nginx-local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - worker
      - worker-storage
    ports:
      - "8080:8080"

  faasm-cli:
    image: ${FAASM_CLI_IMAGE}
    working_dir: /usr/local/code/faasm
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      - worker
      - worker-storage
      - nginx
    environment:
      - UPLOAD_HOST=${UPLOAD_HOST:-upload}
      - INVOKE_HOST=${INVOKE_HOST:-nginx}
      - LOG_LEVEL=debug
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_STATE_HOST=redis-state
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
    volumes:
      - ./:/usr/local/code/faasm/
      - ./dev/faasm/build/:/build/faasm/
      - ./dev/faasm-local:/usr/local/faasm
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

  cpp:
    image: ${CPP_CLI_IMAGE}
    working_dir: /code/cpp
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      - faasm-cli
    volumes:
      - ./clients/cpp:/code/cpp
      - ./dev/cpp/build:/build/cpp
