version: "3"

services:
  redis-state:
    image: kubasz51/faasm-redis:${REDIS_VERSION}

  redis-queue:
    image: kubasz51/faasm-redis:${REDIS_VERSION}

  minio:
    image: kubasz51/faasm-minio:${FAASM_VERSION}
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./dev/minio/data:/data/minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 3

  upload:
    image: kubasz51/faasm-upload:${FAASM_VERSION}
    ports:
      - "8002:8002"
    expose:
      - "5000"
    depends_on:
      - redis-queue
      - redis-state
      - minio
    volumes:
      - ./dev/faasm/build/:${FAASM_BUILD_MOUNT}
    environment:
      - DELTA_SNAPSHOT_ENCODING=pages=64
      - LOG_LEVEL=debug
      - PYTHON_CODEGEN=${PYTHON_CODEGEN}
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_STATE_HOST=redis-state
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  worker:
    image: kubasz51/faasm-worker:${FAASM_VERSION}
    depends_on:
      - upload
    expose:
      - "8080"
      - "5000"
      - "8003-8010"
    ports:
      - "8080"
      - "8086:8086"
    privileged: true
    volumes:
      - ./:/usr/local/code/faasm/
      - ./dev/faasm/build/:${FAASM_BUILD_MOUNT}
      - ./dev/container/shared_store/:/usr/local/faasm/debug_shared_store/
      - ./bin/entrypoint_worker.sh:/entrypoint.sh
    environment:
      - CAPTURE_STDOUT=off
      - CGROUP_MODE=off
      - DELTA_SNAPSHOT_ENCODING=pages=64
      - GLOBAL_MESSAGE_TIMEOUT=600000
      - LOG_LEVEL=debug
      - NETNS_MODE=off
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_STATE_HOST=redis-state
      - STATE_MODE=inmemory
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
      - ENDPOINT_HOST=worker
      - OVERRIDE_CPU_COUNT=1

  worker-storage:
    image: kubasz51/faasm-worker-storage:${FAASM_VERSION}
    depends_on:
      - upload
    expose:
      - "8080"
      - "5000"
      - "8003-8010"
    ports:
      - "8080"
      - "8087:8086"
    privileged: true
    volumes:
      - ./:/usr/local/code/faasm/
      - ./dev/faasm/build/:${FAASM_BUILD_MOUNT}
      - ./dev/container/shared_store/:/usr/local/faasm/shared/
      - ./bin/entrypoint_worker.sh:/entrypoint.sh
    environment:
      - CAPTURE_STDOUT=off
      - CGROUP_MODE=off
      - DELTA_SNAPSHOT_ENCODING=pages=64
      - IS_STORAGE_NODE=1
      - GLOBAL_MESSAGE_TIMEOUT=600000
      - LOG_LEVEL=debug
      - NETNS_MODE=off
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_STATE_HOST=redis-state
      - STATE_MODE=inmemory
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
      - ENDPOINT_HOST=worker-storage
      - OVERRIDE_CPU_COUNT=1

  nginx:
    image: nginx:latest
    volumes:
      - ./deploy/conf/nginx-local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - worker
      - worker-storage
    ports:
      - "8080:8080"

  cpp:
    image: ${CPP_CLI_IMAGE}
    working_dir: /code/cpp
    stdin_open: true
    tty: true
    depends_on:
      - worker
      - upload
    volumes:
      - ./clients/cpp:/code/cpp

  python:
    image: ${PYTHON_CLI_IMAGE}
    working_dir: /code/python
    stdin_open: true
    tty: true
    depends_on:
      - worker
      - upload
    volumes:
      - ./clients/python:/code/python

  # --- Local cluster dev ---
  # The following containers are only needed for local cluster dev
  faasm-cli:
    image: ${FAASM_CLI_IMAGE}
    working_dir: /usr/local/code/faasm
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      - worker
      - worker-storage
      - nginx
    environment:
      - UPLOAD_HOST=${UPLOAD_HOST:-upload}
      - INVOKE_HOST=${INVOKE_HOST:-nginx}
      - LOG_LEVEL=debug
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_STATE_HOST=redis-state
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
    volumes:
      - ./:/usr/local/code/faasm/
      - ./dev/faasm/build/:/build/faasm/
      - ./dev/faasm-local:/usr/local/faasm
