version: "3.8"

services:
  redis-state:
    image: kubasz51/faasm-redis:${REDIS_VERSION}

  redis-queue:
    image: kubasz51/faasm-redis:${REDIS_VERSION}

  minio:
    image: kubasz51/faasm-minio:${FAASM_VERSION}
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./dev/minio/data:/data/minio
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 3s
      retries: 3

  upload:
    image: kubasz51/faasm-upload:${FAASM_VERSION}
    init: true
    ports:
      - "8002:8002"
    expose:
      - "5000"
    depends_on:
      - redis-queue
      - redis-state
      - minio
    restart: on-failure
    volumes:
      - ./:/usr/local/code/faasm/
      - ./dev/faasm/build/:${FAASM_BUILD_MOUNT}
      - ./dev/faasm-local/wasm/:/usr/local/faasm/wasm
      - ./dev/faasm-local/object/:/usr/local/faasm/object
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/kernel/debug/tracing:/sys/kernel/debug/tracing
    environment:
      - CODEGEN_TARGETS=x86_64:skylake;aarch64:thunderx2t99
      - DELTA_SNAPSHOT_ENCODING=pages=64
      - LOG_LEVEL=debug
      - PYTHON_CODEGEN=${PYTHON_CODEGEN:-off}
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_STATE_HOST=redis-state
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
      - ASAN_OPTIONS=verbosity=1:halt_on_error=1
      - TSAN_OPTIONS=halt_on_error=1:suppressions=/usr/local/code/faasm/thread-sanitizer-ignorelist.txt:history_size=7:second_deadlock_stack=1
      - UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8002/ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

  # Distributed worker, used for executing as a local cluster
  worker:
    image: kubasz51/faasm-worker:${FAASM_VERSION}
    init: true
    security_opt:
      - seccomp:unconfined
    # Allows for tracy thread&ctx switch tracking to work better
    pid: "host"
    depends_on:
      - upload
    expose:
      - "8080"
      - "5000"
      - "8003-8010"
    ports:
      - "8080:8080"
      - "8086:8086"
    privileged: true
    volumes:
      - ./:/usr/local/code/faasm/
      - /tmp/faasm-monitor:/var/faasm-monitor
      - ./dev/faasm/build/:${FAASM_BUILD_MOUNT}
      - ./dev/faasm-local/:${FAASM_LOCAL_MOUNT}
      - ./dev/container/shared_store/:/usr/local/faasm/debug_shared_store/
      - ./bin/entrypoint_worker.sh:/entrypoint.sh
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/kernel/debug/tracing:/sys/kernel/debug/tracing
    environment:
      - TINI_SUBREAPER=1
      - CODEGEN_TARGETS=x86_64:skylake;aarch64:thunderx2t99
      - CAPTURE_STDOUT=on
      - CGROUP_MODE=off
      - DELTA_SNAPSHOT_ENCODING=pages=64
      - GLOBAL_MESSAGE_TIMEOUT=600000
      - LOG_LEVEL=debug
      - NETNS_MODE=off
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_STATE_HOST=redis-state
      - SCHEDULER_MONITOR_FILE=/var/faasm-monitor
      - STATE_MODE=redis
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
      - ENDPOINT_HOST=worker
      - ENDPOINT_NUM_THREADS=1
      - OVERRIDE_CPU_COUNT=8
      - VM_ARENA_MODE=${VM_ARENA_MODE:-}
      - ASAN_OPTIONS=verbosity=1:halt_on_error=1
      - TSAN_OPTIONS=halt_on_error=1:suppressions=/usr/local/code/faasm/thread-sanitizer-ignorelist.txt:history_size=7:second_deadlock_stack=1
      - UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1

  worker-storage:
    image: kubasz51/faasm-worker:${FAASM_VERSION}
    init: true
    security_opt:
      - seccomp:unconfined
    # Allows for tracy thread&ctx switch tracking to work better
    pid: "host"
    depends_on:
      - upload
    expose:
      - "8080"
      - "5000"
      - "8003-8010"
    ports:
      - "8080"
      - "8087:8086"
    privileged: true
    volumes:
      - ./:/usr/local/code/faasm/
      - /tmp/faasm-monitor-storage:/var/faasm-monitor-storage
      - ./dev/faasm/build/:${FAASM_BUILD_MOUNT}
      - ./dev/faasm-local/:${FAASM_LOCAL_MOUNT}
      - ./dev/container/shared_store/:/usr/local/faasm/shared/
      - ./bin/entrypoint_worker.sh:/entrypoint.sh
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/kernel/debug/tracing:/sys/kernel/debug/tracing
    environment:
      - TINI_SUBREAPER=1
      - CODEGEN_TARGETS=x86_64:skylake;aarch64:thunderx2t99
      - CAPTURE_STDOUT=off
      - CGROUP_MODE=off
      - DELTA_SNAPSHOT_ENCODING=pages=64
      - IS_STORAGE_NODE=1
      - GLOBAL_MESSAGE_TIMEOUT=600000
      - LOG_LEVEL=debug
      - NETNS_MODE=off
      - MAX_NET_NAMESPACES=100
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_STATE_HOST=redis-state
      - SCHEDULER_MONITOR_FILE=/var/faasm-monitor-storage
      - STATE_MODE=redis
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
      - ENDPOINT_HOST=worker-storage
      - ENDPOINT_NUM_THREADS=1
      - OVERRIDE_CPU_COUNT=8
      - VM_ARENA_MODE=${VM_ARENA_MODE:-}
      - ASAN_OPTIONS=verbosity=1:halt_on_error=1
      - TSAN_OPTIONS=halt_on_error=1:suppressions=/usr/local/code/faasm/thread-sanitizer-ignorelist.txt:history_size=7:second_deadlock_stack=1
      - UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1

  # Load balancer for local cluster
  nginx:
    image: nginx:latest
    volumes:
      - ./deploy/conf/nginx-local.conf:/etc/nginx/nginx.conf:ro

  # C/C++ functions
  cpp:
    image: ${CPP_CLI_IMAGE}
    init: true
    working_dir: /code/cpp
    stdin_open: true
    tty: true
    volumes:
      - ./clients/cpp:/code/cpp
      - ./dev/faasm-local/:${FAASM_LOCAL_MOUNT}

  # Python functions
  python:
    image: ${PYTHON_CLI_IMAGE}
    init: true
    working_dir: /code/python
    stdin_open: true
    tty: true
    volumes:
      - ./clients/python:/code/python
      - ./dev/faasm-local/:${FAASM_LOCAL_MOUNT}

  # Faasm dev
  faasm-cli:
    image: ${FAASM_CLI_IMAGE}
    init: true
    working_dir: /usr/local/code/faasm
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      - redis-state
      - redis-queue
      - minio
    environment:
      - UPLOAD_HOST=${UPLOAD_HOST:-upload}
      - INVOKE_HOST=${INVOKE_HOST:-worker}
      - LOG_LEVEL=debug
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_STATE_HOST=redis-state
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
      - ASAN_OPTIONS=verbosity=1:halt_on_error=1
      - TSAN_OPTIONS=halt_on_error=1:suppressions=/code/faabric/thread-sanitizer-ignorelist.txt:history_size=7:second_deadlock_stack=1
      - UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1
    volumes:
      - ./:/usr/local/code/faasm/
      - ./dev/faasm/build/:${FAASM_BUILD_MOUNT}
      - ./dev/faasm-local/:${FAASM_LOCAL_MOUNT}
      - ${CONAN_CACHE_MOUNT_SOURCE:-./dev/faasm/conan/}:/root/.conan

  # Distributed tests server
  dist-test-server:
    image: ${FAASM_CLI_IMAGE}
    init: true
    working_dir: /build/faasm
    depends_on:
      - redis-queue
      - redis-state
      - minio
      - upload
    environment:
      - LOG_LEVEL=debug
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_STATE_HOST=redis-state
      - OVERRIDE_CPU_COUNT=4
      - CGROUP_MODE=off
      - GLOBAL_MESSAGE_TIMEOUT=120000
      - BOUND_TIMEOUT=60000
    command: ./bin/dist_test_server
    volumes:
      - ./:/usr/local/code/faasm/
      - ./dev/faasm/build/:${FAASM_BUILD_MOUNT}

  # Profiling/ perf testing
  vector:
    image: netflixoss/vector:latest
    depends_on:
      - faasm-cli
    ports:
      - "80:80"
