version: "3"

services:
  # Storage
  redis-state:
    image: kubasz51/faasm-redis:${REDIS_VERSION}
    ports:
      - "6379:6379"

  # Storage
  minio:
    image: kubasz51/faasm-minio:${FAASM_VERSION}
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    extra_hosts:
      - "luna-fast:192.168.3.10"
      - "saturno-fast:192.168.3.20"
      - "kone-fast:192.168.3.30"
    volumes:
      - ./dev/minio/data:/data/minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 3

  # Storage
  upload:
    image: kubasz51/faasm-upload:${FAASM_VERSION}
    ports:
      - "8002:8002"
    depends_on:
      - redis-state
      - minio
    volumes:
      - ./:/usr/local/code/faasm/
      - ./dev/faasm/build/:${FAASM_BUILD_MOUNT}
      - ./dev/faasm-local/wasm/:/usr/local/faasm/wasm
      - ./dev/faasm-local/object/:/usr/local/faasm/object
    environment:
      - DELTA_SNAPSHOT_ENCODING=pages=64
      - LOG_LEVEL=debug
      - PYTHON_CODEGEN=${PYTHON_CODEGEN:-off}
      - REDIS_QUEUE_HOST=${COMPUTE_NODE}
      - REDIS_STATE_HOST=${STORAGE_NODE}
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
    extra_hosts:
      - "luna-fast:192.168.3.10"
      - "saturno-fast:192.168.3.20"
      - "kone-fast:192.168.3.30"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  # Storage
  worker-storage:
    image: kubasz51/faasm-worker-storage:${FAASM_VERSION}
    security_opt:
      - seccomp:unconfined
    # Allows for tracy thread&ctx switch tracking to work better
    pid: "host"
    ulimits:
      nofile:
        soft: 1073741824
        hard: 1073741824
    depends_on:
      - upload
    ports:
      - "8080:8080"
      - "5000:5000"
      - "8003-8010:8003-8010"
      - "8086:8086"
    privileged: true
    volumes:
      - ./:/usr/local/code/faasm/
      - /tmp/faasm-monitor:/var/faasm-monitor
      - ./dev/faasm/build/:${FAASM_BUILD_MOUNT}
      - ./dev/faasm-local/:${FAASM_LOCAL_MOUNT}
      - ./dev/container/shared_store/:/usr/local/faasm/shared/
      - ./bin/entrypoint_worker.sh:/entrypoint.sh
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/kernel/debug/tracing:/sys/kernel/debug/tracing
    environment:
      - CAPTURE_STDOUT=off
      - CGROUP_MODE=off
      - DELTA_SNAPSHOT_ENCODING=pages=64
      - IS_STORAGE_NODE=1
      - GLOBAL_MESSAGE_TIMEOUT=600000
      - LOG_LEVEL=debug
      - NETNS_MODE=off
      - REDIS_QUEUE_HOST=${COMPUTE_NODE}
      - REDIS_STATE_HOST=${STORAGE_NODE}
      - SCHEDULER_MONITOR_FILE=/var/faasm-monitor
      - STATE_MODE=redis
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
      - ENDPOINT_HOST=${STORAGE_NODE}
      - ENDPOINT_NUM_THREADS=4
      - OVERRIDE_CPU_COUNT=12
    extra_hosts:
      - "luna-fast:192.168.3.10"
      - "saturno-fast:192.168.3.20"
      - "kone-fast:192.168.3.30"

  # Both
  cpp:
    image: ${CPP_CLI_IMAGE}
    working_dir: /code/cpp
    stdin_open: true
    tty: true
    depends_on:
      - upload
    environment:
      - UPLOAD_HOST=${STORAGE_NODE}
      - INVOKE_HOST=${COMPUTE_NODE}
    extra_hosts:
      - "luna-fast:192.168.3.10"
      - "saturno-fast:192.168.3.20"
      - "kone-fast:192.168.3.30"
    volumes:
      - ./clients/cpp:/code/cpp

  # Both
  python:
    image: ${PYTHON_CLI_IMAGE}
    working_dir: /code/python
    stdin_open: true
    tty: true
    depends_on:
      - upload
    environment:
      - UPLOAD_HOST=${STORAGE_NODE}
      - INVOKE_HOST=${COMPUTE_NODE}
    extra_hosts:
      - "luna-fast:192.168.3.10"
      - "saturno-fast:192.168.3.20"
      - "kone-fast:192.168.3.30"
    volumes:
      - ./clients/python:/code/python

  # --- Local cluster dev ---
  # The following containers are only needed for local cluster dev
  # Both
  faasm-cli:
    image: ${FAASM_CLI_IMAGE}
    working_dir: /usr/local/code/faasm
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      - worker-storage
    environment:
      - UPLOAD_HOST=${STORAGE_NODE}
      - INVOKE_HOST=${COMPUTE_NODE}
      - LOG_LEVEL=debug
      - REDIS_QUEUE_HOST=${COMPUTE_NODE}
      - REDIS_STATE_HOST=${STORAGE_NODE}
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
    extra_hosts:
      - "luna-fast:192.168.3.10"
      - "saturno-fast:192.168.3.20"
      - "kone-fast:192.168.3.30"
    volumes:
      - ./:/usr/local/code/faasm/
      - ./dev/faasm/build/:/build/faasm/
      - ./dev/faasm-local:/usr/local/faasm
