---

- name: "Add LLVM GPG key"
  become: yes
  apt_key: url=https://apt.llvm.org/llvm-snapshot.gpg.key

- name: "Install LLVM 13 repo"
  become: yes
  apt_repository:
    repo: "deb http://apt.llvm.org/{{ ansible_distribution_release }}/ llvm-toolchain-{{ ansible_distribution_release }}-13 main"
    state: present

- name: "Install LLVM"
  become: yes
  apt:
    name:
      - llvm-13
      - llvm-13-dev
      - llvm-13-tools
      - llvm-13-runtime
      - lld-13
      - lldb-13
      - libc++-13-dev
      - libc++abi-13-dev
    update_cache: yes

- name: "Install Clang"
  become: yes
  apt:
    name:
      - clang-13
      - clangd-13
      - clang-tools-13
      - libclang-13-dev
      - libclang-common-13-dev
      - libclang-cpp13
      - libclang-cpp13-dev
    update_cache: yes

- name: "Install OpenMP"
  become: yes
  apt:
    name:
      - libomp-13-dev
    update_cache: yes

#- name: "Default symlinks"
#  become: yes
#  file:
#    state: link
#    src: "/usr/bin/{{ item }}-13"
#    dest: "/usr/bin/{{ item }}"
#  with_items:
#    - "clang"
#    - "clang++"
#    - "clang-cpp"
#    - "wasm-ld"
#    - "lld"
#    - "llvm-ar"
#    - "llvm-config"
#    - "llvm-nm"
#    - "llvm-ranlib"
